// Extracts platform icons from simple-icons (CC0) into src/content/logos.ts
// so the icon library never ships to the client. Run: node scripts/build-logos.mjs
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";

// key → simple-icons export. Keys are referenced from trafficSources[].icon
const map = {
  meta: "siMeta",
  googleads: "siGoogleads",
  tiktok: "siTiktok",
  youtube: "siYoutube",
  snapchat: "siSnapchat",
  x: "siX",
  pinterest: "siPinterest",
  reddit: "siReddit",
  dv360: "siGoogledisplayandvideo360",
  apple: "siApple",
};

// Hand-drawn geometric marks for brands not in simple-icons.
const extra = {
  linkedin: {
    title: "LinkedIn",
    hex: "0A66C2",
    paths: [
      {
        d: "M20.45 20.45h-3.55v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.36V9h3.41v1.56h.05c.47-.9 1.63-1.85 3.36-1.85 3.6 0 4.27 2.37 4.27 5.45v6.29zM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12zM7.12 20.45H3.56V9h3.56v11.45zM22.22 0H1.77C.79 0 0 .77 0 1.73v20.54C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.73V1.73C24 .77 23.2 0 22.22 0z",
      },
    ],
  },
  microsoft: {
    title: "Microsoft",
    hex: "5E5E5E",
    paths: [
      { d: "M1 1h10.5v10.5H1z", fill: "#F25022" },
      { d: "M12.5 1H23v10.5H12.5z", fill: "#7FBA00" },
      { d: "M1 12.5h10.5V23H1z", fill: "#00A4EF" },
      { d: "M12.5 12.5H23V23H12.5z", fill: "#FFB900" },
    ],
  },
};

const out = {};
for (const [key, exp] of Object.entries(map)) {
  const icon = si[exp];
  if (!icon) throw new Error(`simple-icons export ${exp} not found`);
  out[key] = { title: icon.title, hex: icon.hex, paths: [{ d: icon.path }] };
}
Object.assign(out, extra);

const ts = `/**
 * Platform icons — generated by scripts/build-logos.mjs (do not edit by hand).
 * Sources: simple-icons (CC0) plus two hand-drawn geometric marks.
 * All marks remain the property of their respective owners.
 */
export type LogoPath = { d: string; fill?: string };
export type Logo = { title: string; hex: string; paths: LogoPath[] };

export const logos = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, Logo>;

export type LogoKey = keyof typeof logos;
`;
writeFileSync("src/content/logos.ts", ts);
console.log(`wrote src/content/logos.ts with ${Object.keys(out).length} icons`);
